"""Upgrade

Revision ID: 03b1f8ed06d4
Revises: initial_migration
Create Date: 2026-10-03 06:35:05.636632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b1f8ed06d4'
down_revision: Union[str, None] = 'initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create new tables
    op.create_table('envelopes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('key_id', sa.String(), nullable=False),
        sa.Column('nonce', sa.LargeBinary(), nullable=False),
        sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
        sa.Column('format_version', sa.BigInteger(), nullable=False, server_default='0'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key_id', 'nonce', name='uq_envelopes_key_id_nonce')
    )

    op.create_table('documents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('metadata_envelope_id', sa.String(), nullable=False),
        sa.Column('content_envelope_id', sa.String(), nullable=False),
        sa.Column('byte_length', sa.BigInteger(), nullable=False),
        sa.Column('media_type', sa.String(), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.Column('version', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['content_envelope_id'], ['envelopes.id'], ),
        sa.ForeignKeyConstraint(['metadata_envelope_id'], ['envelopes.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_user_id_updated_at', 'documents', ['user_id', 'updated_at'], unique=False)

    # 2. Add nullable columns to existing tables for data migration
    with op.batch_alter_table('audit_events') as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    with op.batch_alter_table('notes') as batch_op:
        batch_op.add_column(sa.Column('envelope_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.BigInteger(), nullable=True))
    
    # 3. Data Migration
    import uuid
    connection = op.get_bind()
    notes = connection.execute(sa.text("SELECT id, key_id, nonce, ciphertext FROM notes")).fetchall()
    
    for note in notes:
        env_id = str(uuid.uuid4())
        connection.execute(
            sa.text("INSERT INTO envelopes (id, key_id, nonce, ciphertext, format_version) VALUES (:id, :key_id, :nonce, :ciphertext, :fv)"),
            {"id": env_id, "key_id": note[1], "nonce": note[2], "ciphertext": note[3], "fv": 0}
        )
        connection.execute(
            sa.text("UPDATE notes SET envelope_id = :env_id, version = 1 WHERE id = :nid"),
            {"env_id": env_id, "nid": note[0]}
        )

    connection.execute(sa.text("UPDATE audit_events SET source = 'user' WHERE source IS NULL"))

    # 4. Alter columns to non-nullable and drop old columns
    with op.batch_alter_table('audit_events') as batch_op:
        batch_op.alter_column('source', existing_type=sa.String(), nullable=False)

    with op.batch_alter_table('notes') as batch_op:
        batch_op.alter_column('envelope_id', existing_type=sa.String(), nullable=False)
        batch_op.alter_column('version', existing_type=sa.BigInteger(), nullable=False)
        batch_op.create_foreign_key('fk_notes_envelope_id', 'envelopes', ['envelope_id'], ['id'])
        batch_op.drop_constraint('uq_notes_key_id_nonce', type_='unique')
        batch_op.drop_column('key_id')
        batch_op.drop_column('nonce')
        batch_op.drop_column('ciphertext')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('key_id', sa.VARCHAR(), nullable=False))
    op.add_column('notes', sa.Column('nonce', sa.BLOB(), nullable=False))
    op.add_column('notes', sa.Column('ciphertext', sa.BLOB(), nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_unique_constraint('uq_notes_key_id_nonce', 'notes', ['key_id', 'nonce'])
    op.drop_column('notes', 'version')
    op.drop_column('notes', 'envelope_id')
    op.drop_column('audit_events', 'source')
    op.drop_index('ix_documents_user_id_updated_at', table_name='documents')
    op.drop_table('documents')
    op.drop_table('envelopes')
    # ### end Alembic commands ###
